package Vista;

import java.awt.GridLayout;
import java.awt.Image;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class ListaHoteles extends javax.swing.JFrame {

    private final Map<JButton, String> hotelDescriptions = new HashMap<>();

    public ListaHoteles() {
        setTitle("Lista de Hoteles");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Creación de un GridLayout para organizar los componentes en una cuadrícula
        GridLayout gridLayout = new GridLayout(3, 1, 30, 30);
        jPanel1 = new javax.swing.JPanel();
        jPanel1.setLayout(gridLayout);

        // Creación de una etiqueta para el título general
        JLabel titleLabel = new JLabel("Lista de Hoteles El Continental");
        titleLabel.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 24));
        titleLabel.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(titleLabel);

        // Creación de un panel para los botones
        JPanel buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridLayout(2, 2, 30, 30));

        // Creación de botones
        JButton botonMarruecos = createButton("/img/continentalMarruecos.jpg", "Hotel Marruecos");
        JButton botonNY = createButton("/img/continentalNY.jpeg", "Hotel New York");
        JButton botonRoma = createButton("/img/continentalRoma.jpg", "Hotel Roma");
        JButton botonTokyo = createButton("/img/continentalTokyo.jpg", "Hotel Tokyo");

        // Agregar botones al panel de botones
        buttonPanel.add(botonMarruecos);
        buttonPanel.add(botonNY);
        buttonPanel.add(botonRoma);
        buttonPanel.add(botonTokyo);

        // Agregar el panel de botones al panel principal
        jPanel1.add(buttonPanel);

        // Agregar el panel principal al contenido de la ventana
        getContentPane().add(jPanel1);

        // Hacer visible la ventana
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
        this.setSize(700, 700);
    }
    private JButton createButton(String imagePath, String hotelName) {
        // Crear el panel que contendrá la imagen y el texto
        JPanel buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridLayout(2, 1));

        // Crear el botón
        JButton button = new JButton();

        // Agregar ActionListener al botón
        button.addActionListener(e -> {
            String description = hotelDescriptions.get(button);
            JOptionPane.showMessageDialog(ListaHoteles.this, description);
        });

        // Crear la etiqueta para la imagen
        ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
        Image img = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        JLabel imageLabel = new JLabel(icon);
        buttonPanel.add(imageLabel);

        // Crear la etiqueta para el texto
        JLabel textLabel = new JLabel(hotelName);
        buttonPanel.add(textLabel);

        // Agregar el panel al botón
        button.add(buttonPanel);

        // Almacenar la descripción asociada con el botón en el mapa
        hotelDescriptions.put(button, "Bienvenidos al " + hotelName + " de la cadena Continental. Te estamos esperando para que pases una estadia 5 estrellas");

        return button;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Lista de Hoteles El Continental");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(112, 112, 112))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(362, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
              try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaHoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new ListaHoteles().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
